spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/evidenta_populatiei_la_politie
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Configurarea JdbcTemplate
spring.jdbc.template.auto-detect=true

logging.level.org.springframework.security=DEBUG